### ISSUE TITLE
ArrowHelper is missing Date32 support

### ISSUE THREAD

**Issue by kirk-quinbar** [aminebizid/databricks-sql-csharp#1]
Currently the ArrowHelper is missing Date32 support. Any idea what would need to be added to MakeColumn function to add that?

I was thinking something like this. This does get past casting of Date32Array to PrimitiveArray but then i get an error related to argument out of range
                case ArrowTypeId.Date32:
                    var primitiveArrayDate32 = (PrimitiveArray<int>)arrowArray;
                    var valueBufferDate32 = primitiveArrayDate32.ValueBuffer.Memory;
                    var nullBitmapBufferDate32 = primitiveArrayDate32.NullBitmapBuffer.Memory;
                    return new Int32DataFrameColumn(name, valueBufferDate32, nullBitmapBufferDate32, arrowArray.Length, arrowArray.NullCount);

error:
Unhandled exception. System.AggregateException: One or more errors occurred. (Specified argument was out of the range of valid values.)
 ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Microsoft.Data.Analysis.ReadOnlyDataFrameBuffer`1.get_Item(Int32 index)
   at Microsoft.Data.Analysis.PrimitiveColumnContainer`1.get_Item(Int64 rowIndex)
   at Microsoft.Data.Analysis.PrimitiveDataFrameColumn`1.GetTypedValue(Int64 rowIndex)
   at Microsoft.Data.Analysis.PrimitiveDataFrameColumn`1.GetValue(Int64 rowIndex)
   at Microsoft.Data.Analysis.DataFrameRow.GetEnumerator()+MoveNext()
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at DataBricks.Sql.ArrowHelper.BatchToQueue(ConcurrentQueue`1 queue, RecordBatch recordBatch) in C:\Projects\databricks-sql-csharp\src\DataBricks\Sql\ArrowHelper.cs:line 40

**Comment by kirk-quinbar** [comment]
after further review, this error above is not from my Date32 code. I think that works as expected, although the end result is a numeric value. This makes sense based on the description of date32: Create instance of 32-bit date (days since UNIX epoch 1970-01-01).

the error is  occurring somewhere in your code or the arrow code when it tries to pull boolean values. looks like string, date32 and int all work as expected.

**Comment by aminebizid** [comment]
I use this code for datetimes:
```cs
private readonly DateTimeOffset _pivotDate = new DateTimeOffset(1970, 1, 1, 0, 0, 0, TimeSpan.Zero);
var timestamp = _pivotDate.AddMilliseconds(Convert.ToDouble((ulong)record[0])/1000)
```
